name: Build, Push, and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Construir y enviar la imagen a Docker Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: thewadjet/budget-app:latest

    # 4. Conectar y desplegar en EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull thewadjet/budget-app:latest
          docker stop budget-app || true
          docker rm budget-app || true
          docker run -d --name budget-app -p 3000:3000 thewadjet/budget-app:latest
